### ISSUE TITLE
Friend's can't join my gameserver!!!

### ISSUE THREAD

**Issue by XYABOIZ** [zombman/backend#10]
Im able to press play and enter into the game but my friend is connected to my gameserver but wont join.

**Comment by zombman** [comment]
More information please

**Comment by XYABOIZ** [comment]
> More information please

My friends cant join my gameserver

**Comment by httpsfortyfive** [comment]
Matchmaking works just as fine, you probably set it up incorrectly.

**Comment by XYABOIZ** [comment]
> Matchmaking works just as fine, you probably set it up incorrectly.

How do I set it up correctly? Is there anyway to change the matchmaker ip?

**Comment by zombman** [comment]
DUPLICATE
