### ISSUE TITLE
User editor causes blank screen

### ISSUE THREAD

**Issue by katopiler** [zombman/backend#11]
When i click user editor, it results in a green screen.
![image](https://github.com/zombman/backend/assets/64710752/de2a6a5c-c56c-458d-a3e5-c853e5725c8e)

**Comment by AySaturn** [comment]
run it on localhost using a browser, rn it does not work through the launcher or using an ip mainly for everyone to use

**Comment by zombman** [comment]
will be fixed thank you for bringng this up

**Comment by XYABOIZ** [comment]
I had this problem before, you prob use an IP instead of localhost. Just do localhost: (your port) /login

**Comment by katopiler** [comment]
> Can u open the console and send me info Maybe use the latest commit it should be fixed

the console of the docker container?

**Comment by katopiler** [comment]
just redeployed it and reset the databace and admin password and when i login as user: admin pass: admin it says incorrect

**Comment by zombman** [comment]
This is fixed by using https or localhost. The app uses the inbuilt cryptography module which is only available if https is used.
