### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by XYABOIZ** [zombman/backend#12]
if people are connected to my backend, they can see the item shop and stuff but cant get into a game but when they are not connected to the backend, its the opposite

**Comment by zombman** [comment]
more info please

**Comment by XYABOIZ** [comment]
> more info please

I connect to my backend and I can see the item shop and every other feature. I can also join a game without a problem but when other people are connected to my backend they have the features like the item shop but when they press play, they dont join my game server. When others are NOT connected to MY backend, they dont have any features and they dont see the item shop BUT they can join my game server when they press play.

**Comment by zazdev123** [comment]
the IP you have setup for the gameserver is your public IP and not your local IP, right?

**Comment by XYABOIZ** [comment]
> the IP you have setup for the gameserver is your public IP and not your local IP, right?

Yes

**Comment by zombman** [comment]
I mean more info as in console logs and fort logs

**Comment by XYABOIZ** [comment]
> I mean more info as in console logs and fort logs

Where do I get that?

**Comment by TimmieDevelops** [comment]
> > more info please
> 
> I connect to my backend and I can see the item shop and every other feature. I can also join a game without a problem but when other people are connected to my backend they have the features like the item shop but when they press play, they dont join my game server. When others are NOT connected to MY backend, they dont have any features and they dont see the item shop BUT they can join my game server when they press play.

let me guess is it 127.0.0.1:7777?
