### ISSUE TITLE
Please Make The Skins Work Again

### ISSUE THREAD

**Issue by XYABOIZ** [zombman/backend#13]
I have tried it multiple times and skins dont work anymore. Skins are one of the most important parts of a backend.Please add them back.

**Comment by zombman** [comment]
????????????????????????? Skins work fine and provide more info

**Comment by XYABOIZ** [comment]
> ????????????????????????? Skins work fine and provide more info

I have installed the backend properly and set it up properly aswell, but whenever I am in-game and I buy something from the item shop, it goes into my locker, I equip it then I join a gameserver but the skin dosent appear even tho I have NO MCP off. I go back to the lobby and for no reason, my skins disappear from my locker.  BUT something that I find weird is that, when i give myself all the skins from the website and I equip a skin inside the game and I rejoin the gameserver, the skin appears.

**Comment by zombman** [comment]
hmmm
maybe because
u need to login to backend before u inject the server dll

**Comment by XYABOIZ** [comment]
> hmmm maybe because (sarcasm) u need to login to backend before u inject the server dll

Thats what I have been doing.

**Comment by zombman** [comment]
NOO omg pls ur such a skid
Do u understand that u need to LOGIN like PUT A USERNAME AND PASSWORD
e.g.
server@.
serverpass

then when ur in lobby inject server.dll
then itl work
