### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by XYABOIZ** [zombman/backend#6]
When I type "./server" and it says the permission is denied and then my anti virus says that theres something that is malware and its severe.

**Comment by zombman** [comment]
There is 0 malware

**Comment by XYABOIZ** [comment]
> There is 0 malware

I just get an error now

![Capture](https://github.com/zombman/backend/assets/129079121/015fe104-494c-4568-8483-b99b1673f879)

**Comment by zombman** [comment]
Can you read. You have not supplied a valid databse

**Comment by XYABOIZ** [comment]
> Can you read. You have not supplied a valid databse

how do I fix that?

**Comment by zombman** [comment]
Watch the steup tutorial

**Comment by XYABOIZ** [comment]
> Watch the steup tutorial

I did and copied everything, the first time it worked but then it kept giving me an error. I did reset the ProgreSQL

**Comment by XYABOIZ** [comment]
???

**Comment by XYABOIZ** [comment]
I got it to work but when I try to login with admin admin, it says that they are wrong credentials.

**Comment by XYABOIZ** [comment]
@zombman

**Comment by XYABOIZ** [comment]
Fixed it

**Comment by XYABOIZ** [comment]
How do other people register for an account?

**Comment by XYABOIZ** [comment]
Im getting an error saying that I can't login to Fortnite servers

**Comment by XYABOIZ** [comment]
Why are the skins not showing in-game?

**Comment by XYABOIZ** [comment]
Fixed it

**Comment by XYABOIZ** [comment]
Where can I get a gameserver

**Comment by XYABOIZ** [comment]
How do friends join?

**Comment by XYABOIZ** [comment]
> Fixed it

?

**Comment by zombman** [comment]
Old
